version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASS: mypass
      DB_NAME: mydb
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  pgdata: